name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code_quality:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpstan, cs2pr

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPStan
        run: composer stan

      - name: Check code style (ECS)
        run: vendor/bin/ecs check 

  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: app
        ports:
          - 5432:5432
      redis:
        image: redis:6.0
        ports:
          - 6379:6379
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        run: composer test

  docker_build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [code_quality, tests]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/task-manager:latest" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/task-manager:latest"

